---
abstract: ~
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ShavianOrg
no_index:
  directory:
    - inc
    - share
requires:
  DBI: 0
  File::ShareDir: 0
  Template: 0
version: undef
